baseURL: "https://samirpaulb.github.io/"
title: Samir Paul
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# mainsections: ["posts"]
googleAnalytics: G-CP4QE6ZEV0

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Search
          url: search/
          weight: 15

outputs:
  home:
    - HTML
    - RSS
    - JSON

# keep it here as .Site.DisqusShortname is referred
disqusShortname: samirpaul

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Technical blog for developers. Computer Science, Data Structures Algorithms, Networking, Artificial Intelligence and Coding Interview Prep."
  author: Samir Paul
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: false
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  TocOpen: true
  comments: true
  hidemeta: false
  hideFooter: false
  images: ["/screenshot.png",]

  profileMode:
    enabled: false
    title: Samir Paul
    imageUrl: "/avatar.webp"
    imageTitle: Samir Paul
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: About Me
        url: about
      - name: Blog
        url: posts

  homeInfoParams:
    Title: "Hi there👋"
    Content: >
      - **Welcome to my technical blog!**

      - Here I write content about Computer Science, Data Structures Algorithms, Networking, Artificial Intelligence and Coding Interview Preparation.

      - <small><i>All contents on this site are my own personal opinions/ideas and do not reflect the opinions of my institutions/organizations.</i></small>

  socialIcons:
    - name: LinkedIn
      title: Connect with me on LinkedIn
      url: "https://linkedin.com/in/SamirPaul"
    - name: GitHub
      title: View Source on Github
      url: "https://github.com/SamirPaulb"
    - name: X
      title: Connect on X/Twitter
      url: "https://twitter.com/SamirPaulb"
    - name: Instagram
      title: Follow me on Instagram
      url: "https://www.instagram.com/SamirPaulb"
    - name: RSS
      title: RSS Feeds
      url: "index.xml"

  # editPost:
  #   URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: "vJAOBxbJTCK2vXG-hLFeGsoC9hXgFlCpuJJ8AcJLROQ"
    bing:
      SiteVerificationTag: "1A92FC2EC113F8616A21D76DA684A133"
    yandex:
      SiteVerificationTag: "fe6a06c57be84984"
    pinterest:
      SiteVerificationTag: "24bac6e1fbf1750de40d59bb788d9dd9"
    norton:
      SiteVerificationTag: "j7w6winrjctu1-mcfpposj35ae-2txdr3qhqt9edmam0gf98j9qtpixft-qv452wjund2cyc9jacd71w81ee6addfggzcmr-affl9b3eblxul7768d9d5dh2fjkupp1h"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  cover:
      hidden: false # hide everywhere but not in structured data
      hiddenInList: true # hide on list pages and home
      hiddenInSingle: false # hide on single page
      linkFullImages: false
      image: "https://scdn.netlify.app/blog-featured-image-samirpaul-in-blog.webp"
      alt: "blog-featured-image"
      caption: "Technical blog"

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
